{ config, pkgs, ... }:

{
  imports = 
    [
      ../hardware-configuration.nix  # include local hardware scan as generated by nixos-generate-config
      ../secrets.nix  # include local secrets
      ../base.nix
      ../fragments/home-manager.nix
      ../fragments/users.nix
      ../templates/workstation-all.nix
    ];

  
}