{ config, pkgs, ... }:

{
  imports = 
    [
      ../hardware-configuration.nix  # include local hardware scan as generated by nixos-generate-config
      ../secrets.nix  # include local secrets
      ../base.nix
      ../fragments/home-manager.nix
      ../fragments/users.nix
      ../fragments/lxc.nix
      ../templates/workstation.nix
    ];

  # running inside lxc
  boot.isContainer = true;
  mine.lxc.enable = true
  
  # Enable touchpad support (enabled default in most desktopManager).
  services.xserver.libinput.enable = true;
}